### PR TITLE
Version 1.1.0

### LINKED ISSUE #21: Enhance comment's metrics accuracy
### Expected behavior
Number of comment lines must be exact.

### Actual behavior
Number of comment lines is not exact because of the computation is based on i-Code CommentRatio.
Waiting for i-Code 3.1.0.

### Steps to reproduce behavior
Launch i-Code.

### Detection version
1.0.0-alpha

### LINKED ISSUE #28: i-Code CNES auto-launch
### Expected behavior
User should be able to choose to autolaunch i-Code CNES on analysis.

### Actual behavior
User has to run i-Code CNES by himself before using sonar icode

### Steps to reproduce behavior
/

### Detection version
1.0.2

### LINKED ISSUE #29: Analysis failed if an issue on a unknown rule is present in the result file
### Expected behavior
Analysis should warn the user of the read of a unknown issue and continue import results.

### Actual behavior
Analysis failed if an issue on a unknown rule is present in the result file.

### Steps to reproduce behavior
Rule analysis on a file with exotic rule ids.

### Detection version
1.0.2

### LINKED ISSUE #30: Add new rules from i-Code 3.1.0
### Expected behavior
sonaricode 1.1.0 should fully support i-Code 3.1.0 and its new rules.

### Actual behavior
Supported rules are those of i-Code 3.0.1.

### Detection version
1.0.2

### PR DESCRIPTION
**Pull request by begarco**
### Fixes :
- Fix #21 
- Fix #28 
- Fix #29 
- Fix #30

### CODE REVIEW

File: src/main/java/fr/cnes/sonar/plugins/icode/check/ICodeSensor.java [hunk 1]
```diff
@@ -97,6 +100,33 @@ public void execute(SensorContext sensorContext) {
...
+            LOGGER.info("Running i-Code CNES and generating results to "+ outputPath);
+            try {
+                final Process icode =  Runtime.getRuntime().exec(command);
+                int success = icode.waitFor();
+                if(0!=success){
+                    final String message = String.format("i-Code CNES auto-launch analysis failed with exit code %d.",success);
+                    throw new ICodeException(message);
+                }
+                LOGGER.info("Auto-launch successfully executed i-Code CNES.");
+            } catch (InterruptedException | IOException | ICodeException e) {
```
Comment (begarco) [inline src/main/java/fr/cnes/sonar/plugins/icode/check/ICodeSensor.java]: Bug Bug: Either re-interrupt this method or rethrow the "InterruptedException". ([squid:S2142](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS2142))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonaricode&pullRequest=33&issues=AWXXG66W_eEZPtUm_0Ak&open=AWXXG66W_eEZPtUm_0Ak)

[ISSUE_KEY]: AWXXG66W_eEZPtUm_0Ak
