### PR TITLE
Fix #34 #35 #36

### LINKED ISSUE #34: sonaricode properties must be editable at project level
### Expected behavior
sonaricode properties must be editable at project level.

### Actual behavior
sonaricode properties are only editable at general level.

### Steps to reproduce behavior
Try to edit a property for a specific project.

### Detection version
1.1.0

### LINKED ISSUE #35: Code coverage must be > 80.0%
### Expected behavior
Code coverage must be > 80.0%.

### Actual behavior
Code coverage is about 40%.

### Steps to reproduce behavior
See SonarCloud.

### Detection version
1.1.0

### LINKED ISSUE #36: Report files may be out of sources and tests files
### Expected behavior
Result files can be every where in the project base directory.

### Actual behavior
Result files has to be in indexed files to be found.

### Steps to reproduce behavior
Launch sonar-scanner on a project where:
```
sonar.sources=src/
sonar.tests=test/
sonar.framac.reports.path=result.csv
```

### Detection version
1.1.0

### PR DESCRIPTION
**Pull request by begarco**
### Fixes :
- Fix #34 
- Fix #35 
- Fix #36

### CODE REVIEW

File: src/test/java/fr/cnes/sonar/plugins/icode/exceptions/ICodeExceptionTest.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with sonar-icode-cnes-plugin.  If not, see <http://www.gnu.org/licenses/>.
+ */
+package fr.cnes.sonar.plugins.icode.exceptions;
+
+import org.junit.Assert;
+
+public class ICodeExceptionTest {
```
Comment (begarco) [inline src/test/java/fr/cnes/sonar/plugins/icode/exceptions/ICodeExceptionTest.java]: Code Smell Code Smell: Add some tests to this class. ([squid:S2187](https://sonarcloud.io/organizations/lequal/rules#rule_key=squid%3AS2187))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fr.cnes.sonarqube.plugins%3Asonaricode&pullRequest=37&issues=AWXs1igg2IDoRcZ5vwWn&open=AWXs1igg2IDoRcZ5vwWn)

[ISSUE_KEY]: AWXs1igg2IDoRcZ5vwWn
